const themes = ['light', 'dark'];
const color_palette = {
    'light' : {
        '--body-background-color': '#F4F4F8',
        '--h2-color': '#000000',
        '--label_color' : '#000000',
        '--box-background-color' : '#ffffff',
        '--sorting_nav-background-color' : '#1E1E38',
        '--style_btn-color' : '#ffffff',
        '--style_btn-border-color' : '#ffffff',
        '--style_btn_hover-background-color' : '#ffffff',
        '--style_btn_hover-color' : '#000000', 
        '--btn_override-background-color' : '#1E1E38',
        '--btn_override-border-color' : '#1E1E38',
        '--btn_override_hover-background-color' : '#177e89',
        '--btn_override_hover-border-color' : '#177e89',
        '--dropdown_item_active-background-color' : '#177e89',
        '--dropdown_menu-background-color' : '#ffffff',
    },
    'dark' : {
        '--body-background-color': '#F4F4F8',
        '--h2-color': '#000000',
        '--label_color' : '#000000',
        '--box-background-color' : '#ffffff',
        '--sorting_nav-background-color' : '#177e89',
        '--style_btn-color' : '#ffffff',
        '--style_btn-border-color' : '#ffffff',
        '--style_btn_hover-background-color' : '#ffffff',
        '--style_btn_hover-color' : '#000000', 
        '--btn_override-background-color' : '#177e89',
        '--btn_override-border-color' : '#177e89',
        '--btn_override_hover-background-color' : '#5bc0be',
        '--btn_override_hover-border-color' : '#5bc0be',
        '--dropdown_item_active-background-color' : '#5bc0be',
        '--dropdown_menu-background-color' : '#ffffff',
    },
};